title: Human-Robot Contact and Manipulation
email: hrcm-organizers@googlegroups.com
description: Workshop Series on Human-Robot Contact and Manipulation
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']

# Google Analytics
google_analytics: G-XT7QDYQEKC

